title: "質問のタイトル"
labels: [general]
body:
- type: checkboxes
  attributes:
    label: 質問の前に...
    options:
      - label: GitHub ID を TechTrain のプロフィールに設定しましたか？
        required: true
      - label: 同様の質問が既にされていないか確認しましたか？
        required: true
- type: input
  attributes:
    label: TechTrain のユーザー ID (数字)
    description: TechTrain のユーザー ID を入力してください。TechTrain マイページ（https://techtrain.dev/mypage）で確認できます。
  validations:
    required: true
- type: markdown
  attributes: 
    value: Railwayに関する質問はそれぞれ個別のカテゴリを使用してください。それ以外の質問はこのカテゴリを利用してください。
- type: dropdown
  attributes:
    label: トピックを選択
    description: 何について質問したいですか？
    options:
      - "TechTrain全般"
      - "Railway全般"
      - "提案"
      - "その他"
  validations:
    required: true
- type: textarea
  attributes:
    label: 質問内容
    description: こちらに本文を記入してください。
  validations:
    required: true