title: "質問のタイトル"
labels: [general]
body:
- type: markdown
  attributes: 
    value: Railwayに関する質問はそれぞれ個別のカテゴリを使用してください。それ以外の質問はこのカテゴリを利用してください。
- type: dropdown
  attributes:
    label: トピックを選択
    description: 何について質問したいですか？
    options:
      - "TechTrain全般"
      - "Railway全般"
      - "提案"
      - "その他"
  validations:
    required: true
- type: textarea
  attributes:
    label: 質問内容
    description: こちらに本文を記入してください
  validations:
    required: true