title: "Station[番号] - [質問のタイトル]"
labels: []
body:
- type: checkboxes
  attributes:
    label: 質問の前に...
    options:
      - label: 同様の質問が既にされていないか確認しましたか？
        required: true
- type: input
  attributes:
    label: TechTrainのユーザーID（数字）
    description: TechTrainのユーザーIDを入力してください。https://techtrain.dev/mypage/profile で確認できます。
  validations:
    required: true
- type: input
  attributes:
    label: GitHubID
    description: GitHubのIDを入力してください。
  validations:
    required: false
- type: dropdown
  attributes:
    label: Station番号
    description: どのStationについて質問しますか？
    options:
      - "Station1"
      - "Station2"
      - "Station3"
      - "Station4"
      - "Station5"
      - "Station6"
      - "Station7"
      - "Station8"
      - "Station9"
      - "Station10"
      - "Station11"
      - "Station12"
      - "Station13"
      - "Station14"
      - "Station15"
  validations:
    required: true
- type: input
  attributes:
    label: 実行環境（openjdkバージョン）
    description: バージョン番号を入力してください。`java -version`で確認できます。
  validations:
    required: true
- type: input
  attributes:
    label: 実行環境（mavenバージョン）
    description: バージョン番号を入力してください。`mvn -version`で確認できます。
  validations:
    required: true
- type: textarea
  attributes:
    label: 現在起こっていること（説明 / エラー文のコピペ、スクショ / エディタ含め、コード全体が写っているスクショ）
    description: 上記が揃っているとディスカッションが進めやすいです。
  validations:
    required: true
- type: textarea
  attributes:
    label: 再現するための手順
    description: 実行したコマンドなど、行った操作を順番に記述してください。
  validations:
    required: false
- type: textarea
  attributes:
    label: 実現したいことは何か
    description: できるだけ「クリアしたい」以外の言葉で、どうなって欲しいのかをプログラム側の視点から書いてみましょう。
  validations:
    required: false
- type: textarea
  attributes:
    label: 自分で調べて行ったこと
    description: ここまで調べてそれを踏まえた上でこうしたけど、ここがわからなかった（できなかった）、など具体的に書いてみましょう。
  validations:
    required: false